### ISSUE TITLE
Can SWR import resources from the Impact4soil platform?

### ISSUE THREAD

**Issue by pvgenuchten** [soilwise-he/harvesters#52]
Impact4soil has recently been introduced, it is a deliverable of the [orcasa project](https://cordis.europa.eu/project/id/101059863/es). Plans exist within the consortium to let SWR benefit from technology or content of the impact4soil platform. For that reason it needs to be clarified if any constraints (authorization, attribution, embargo) apply to those contributions of the impact4soil platform.

A meeting between the technical teams of both platforms will be scheduled in october 2024, would be good if this issue is clarified before that date.

Content of Impact4soil is maintained by a group of expert editors, which evaluate each potential resource on its relevance to policy makers.

**Comment by pvgenuchten** [comment]
Impact4soil captures minimal metadata on resources, and forwards the user to the source as soon as possible to assess further details.

- For resources which are identified by a DOI, additional metadata can be retrieved from OpenAire or crossref
- The harvester could trigger a harvest of the secondary platform to capture additional metadata. Since we don't know what technology is used in the secondary platform, we expect successfull retrieval in limited cases
- The results of impact4soil can also be used to increase the confidence on existing records, in case a resource described in impact4soil is already available in SWR via alternative route.

**Comment by EmilieVrot** [comment]
Hello Paul,

Regarding data from Impact4Soil, we have two types of date: 
- The firtst type are data coming from external sources (for instances some maps, data of the practices module, data of the datasets module). Are you interested to retrieve these data ? If so, some sources are open access, for other authorizations should be asked (WOCAT, FAO, SoilsRevealed, etc.).
- The second type are data that we have "produced" for Impact4Soil: 
           - The MRV layers
           - Scientific evidence
           - Network

In order to correctly prepare who should be attending the meeting of October 7th, can you give me more details about the data you want to retrieve in Soilwise?

Thanks,
Emilie

**Comment by pvgenuchten** [comment]
For data produced by Orcasa, I assume it to be deposited in dataverse/zenodo and then included in impact4soil? And thus using a similar approach to be harvested then other datasets?
